
# This is your Supabase config file

project_id = "hqrqxedofrylfuylskvr"

[functions.admin-feature-flags]
verify_jwt = true

[functions.admin-system-settings]
verify_jwt = true

[functions.admin-system-logs]
verify_jwt = true
