// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrqxedofrylfuylskvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcnF4ZWRvZnJ5bGZ1eWxza3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDk0NDEsImV4cCI6MjA2MTUyNTQ0MX0.ehRepPfQ3sbTeVUHt9atF4UedZRvKSzli4-Vj_jDGg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);